### PR TITLE
Use control schema for messages

### LINKED ISSUE #48: Wrong order of arguments in AddPortMapping
I found your library a few days ago and I struggled to get your examples to work with my router, I always ended up with error code 402.

After comparing the library with miniupnp (which works with my router), I found out that the order of arguments that are sent to the router is different. With your library, the body looks like:

    <?xml version="1.0"?>
    <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
        <s:Body>
            <u:AddPortMapping xmlns:u="urn:schemas-upnp-org:service:WANIPConnection:1">
                <NewProtocol>TCP</NewProtocol>
                <NewExternalPort>12345</NewExternalPort>
                <NewInternalClient>192.168.0.115</NewInternalClient>
                <NewInternalPort>12345</NewInternalPort>
                <NewLeaseDuration>60</NewLeaseDuration>
                <NewPortMappingDescription>crust</NewPortMappingDescription>
                <NewEnabled>1</NewEnabled>
                <NewRemoteHost></NewRemoteHost>
            </u:AddPortMapping>
        </s:Body>
    </s:Envelope>

While miniupnp produces the following body:

    <?xml version="1.0"?>
    <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
        <s:Body>
            <u:AddPortMapping xmlns:u="urn:schemas-upnp-org:service:WANIPConnection:1">
                <NewRemoteHost></NewRemoteHost>
                <NewExternalPort>12345</NewExternalPort>
                <NewProtocol>TCP</NewProtocol>
                <NewInternalPort>12345</NewInternalPort>
                <NewInternalClient>192.168.0.115</NewInternalClient>
                <NewEnabled>1</NewEnabled>
                <NewPortMappingDescription>libminiupnpc</NewPortMappingDescription>
                <NewLeaseDuration>60</NewLeaseDuration>
            </u:AddPortMapping>
        </s:Body>
    </s:Envelope>

Note, that only the order of arguments is different. In fact, this is the only reason, why miniupnp works, while your library doesn't.

The routers that provide UPnP functionality also provide a schema document, describing the actions and arguments. According to the Spec (https://openconnectivity.org/upnp-specs/UPnP-arch-DeviceArchitecture-v2.0-20200417.pdf, page 79):

> Every  “in”  argument  in  the  definition  of  the  action  in  the  service  description  shall be  included,  _in  the  same  order  as  specified_  in  the  service  description (SCPD) that is available from the device.

I am currently working on a method to parse this SCPD (XML) and generate the Action body exactly as requested. Would you be willing to include this as a Pull-Request once I am done? Or are you by chance already working on the same issue?

(EDIT: Fixed wrong page number and description)

### PR DESCRIPTION
**Pull request by FloGa**
According to the specification for [UPnP Devices][1], the arguments for the control actions need to match the order of arguments as desribed in the schema. To achieve that, we retrieve the schemas when searching for a compitable gateway and use the appropriate schema for each action to build the arguments properly.

Fixes #48.
    
[1]: https://openconnectivity.org/upnp-specs/UPnP-arch-DeviceArchitecture-v2.0-20200417.pdf

### CODE REVIEW

File: src/aio/search.rs [hunk 1]
```diff
@@ -95,81 +107,147 @@ impl SearchFuture {
...
         let c = std::io::Cursor::new(&resp);
 
         // Parse control URL out of body
-        let url = parsing::parse_control_url(c)?;
+        let urls = parsing::parse_control_urls(c)?;
+
+        Ok(urls)
+    }
+
+    fn request_schemas(
```
Comment (sbstp) [inline src/aio/search.rs:122]: Do you think that using async would make the code simpler and cleaner here? I have no issue whatsoever with dropping the raw future implementations and using async functions for clarity.

File: src/aio/search.rs [hunk 2]
```diff
@@ -95,81 +107,147 @@ impl SearchFuture {
...
+        debug!("handling schema response");
+        let c = std::io::Cursor::new(&resp);
+        parsing::parse_schemas(c)
     }
 }
 
 impl Future for SearchFuture {
     type Output = Result<Gateway, SearchError>;
 
     fn poll(mut self: Pin<&mut Self>, cx: &mut Context) -> Poll<Result<Gateway, SearchError>> {
```
Comment (sbstp) [inline src/aio/search.rs:150]: If you'd like to turn this into an async function as well, I think it could be much cleaner. You don't have to if you don't feel like it though.

File: src/common/messages.rs [hunk 3]
```diff
@@ -35,90 +46,103 @@ pub fn format_get_external_ip_message() -> String {
...
+            let value = match argument.as_str() {
+                "NewEnabled" => 1.to_string(),
+                "NewExternalPort" => external_port.to_string(),
+                "NewInternalClient" => local_addr.ip().to_string(),
+                "NewInternalPort" => local_addr.port().to_string(),
+                "NewLeaseDuration" => lease_duration.to_string(),
+                "NewPortMappingDescription" => description.to_string(),
+                "NewProtocol" => protocol.to_string(),
+                "NewRemoteHost" => "".to_string(),
+                _ => panic!("Nope"),
```
Comment (sbstp) [inline src/common/messages.rs:68]: Can we just ignore the parameter instead of panicking? I don't think a library should panic in these cases. Either we report an error or just ignore it and log a warning.

Unless the parameters are filtered somewhere else where I missed it. The input comes from the router and could make the program panic.

Comment (FloGa) [reply src/common/messages.rs:68]: Ah, you are totally right, I accidently left this `panic` in the code, I intended to delete it before the PullRequest. A warning to the logger / stderr would be the proper way to go here. In case we missed arguments, we get complaints from the router anyway.

File: src/aio/search.rs (hunk 1 above)
Comment (FloGa) [reply src/aio/search.rs:122]: Yes, definitely. I just wanted to preserve as much of your code as possible, so as not to rewrite the whole story. But if you are okay with it, I will try a more `async` approach, without the `Future` implementation.

File: src/aio/search.rs (hunk 2 above)
Comment (FloGa) [reply src/aio/search.rs:150]: Yes, I can rewrite it. As I said, I wanted to preserve much of the code, more so because it was my first time actually working with asynchronous Rust and I didn't know the best practices. But I am positive that I can make it more readable with a nice `async/.await` approach.

File: src/common/messages.rs (hunk 3 above)
Comment (sbstp) [reply src/common/messages.rs:68]: We already have the log library in the deps, `warn!` should do it.

Comment (FloGa) [reply src/common/messages.rs:68]: Yep, working on it right now. ;-)

**Comment by FloGa** [comment]
Hi Simon, I rewrote the aio.search module, this time without the Future implementation and just with `async/.await`.

File: src/aio/gateway.rs [hunk 4]
```diff
@@ -200,6 +198,7 @@ impl Gateway {
         self.perform_request(
             messages::ADD_PORT_MAPPING_HEADER,
             &messages::format_add_port_mapping_message(
+                self.control_schema.get("AddPortMapping").unwrap(),
```
Comment (sbstp) [inline src/aio/gateway.rs:201]: This unwrap is safe?

File: src/aio/gateway.rs [hunk 5]
```diff
@@ -245,7 +244,11 @@ impl Gateway {
         let res = self
             .perform_request(
                 messages::DELETE_PORT_MAPPING_HEADER,
-                &messages::format_delete_port_message(protocol, external_port),
+                &messages::format_delete_port_message(
+                    self.control_schema.get("DeletePortMapping").unwrap(),
```
Comment (sbstp) [inline src/aio/gateway.rs:248]: Ditto?

**Comment by sbstp** [comment]
Looks good, I just have a few comments about the unwraps.

File: src/aio/gateway.rs (hunk 4 above)
Comment (FloGa) [reply src/aio/gateway.rs]: Ah, good catch. If for whatever reason the router does not report a schema for the requested action, then this call to `HashMap.get` will panic.

I rewrote it to instead propagate a dedicated RequestError variant.

File: src/aio/gateway.rs (hunk 5 above)
Comment (FloGa) [reply src/aio/gateway.rs]: See my [previous comment](https://github.com/sbstp/rust-igd/pull/49#discussion_r422557050). I also made the same mistake in the synchronous version of Gateway and fixed it there, too.

**Comment by FloGa** [comment]
I rewrote the unchecked `unwrap`s and replaced them with a proper Error variant for unsupported actions. Maybe this case will never occur, but who knows, what broken hardware / firmware is out there ...

**Comment by sbstp** [comment]
Looks! I'm gonna go a bit more testing and then merge. Are you ok with a squash merge?

**Comment by FloGa** [comment]
> Are you ok with a squash merge?

Personally, I don't like squash merges. It creates one huge commit, that is difficult to read and understand and it makes `git bisect` nearly impossible to use, should the need arise. I won't stop you from doing one though, but in my experience you will be happier with normal merges.

**Comment by sbstp** [comment]
I usually have a workflow that works well with squashes. I felt like I should ask here because you put a lot of care into making clean commits, so I won't squash it.

**Comment by FloGa** [comment]
> you put a lot of care into making clean commits

Thanks, it is exactly because of the reason I mentioned and it fits well in *my* workflow.

You should choose a method that fits with *your* usual workflow, I am fine with either way. :-)

**Comment by sbstp** [comment]
Thanks, I've published 0.11.0 with this fix.

**Comment by FloGa** [comment]
Great to hear, thank you very much!
